language: php

php:
  - 5.5
  - 5.6

install:
  - make travis-install

script:
  - make travis-script

#notifications:
#  slack:
#    rooms:
#      - {{ CHANNEL_INTEGRATION_TOKEN }}
#    on_success: change
#    on_failure: always
#    on_start: never
